services:
  - type: web
    name: brandbrew-app
    runtime: docker
    plan: free
    region: oregon
    dockerfilePath: ./Dockerfile
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4o-mini
      - key: CLERK_SECRET_KEY
        sync: false
      - key: CLERK_ISSUER_URL
        value: https://hot-walleye-4581.clerk.accounts.dev
      - key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
        value: pk_test_aG90LXdhbGxleWUtNDU4MS5jbGVyay5hY2NvdW50cy5kZXYk
      - key: DATABASE_URL
        value: /app/helium.db
